qrcode:
  name: 生成二维码
  description: 使用【HomeAssistant家庭助理】小程序扫码关联
  fields:
    uid:
      name: 用户ID
      description: 请在微信公众号中回复“打开控制模式”获取
      required: true
      selector:
        text:
    topic:
      name: 订阅主题
      description: 请在微信公众号中回复“打开控制模式”获取
      required: true
      selector:
        text: