blueprint:
  name: 微信事件
  description: 接收微信发送的图片和视频（模板内包含变量  临时链接：{{url}}）
  domain: automation
  source_url: https://github.com/shaonianzhentan/ha_wechat/blob/main/blueprints/ha_wechat.yaml
  input:
    image:
      name: 图片
      description: 微信图片
      default: []
      selector:
        action: {}
    video:
      name: 视频
      description: 微信视频
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: ha_wechat
action:
- variables:
    type: '{{ trigger.event.data.data.type }}'
    url: '{{ trigger.event.data.data.url }}'
- choose:
  - conditions:
    - '{{ type == "image" }}'
    sequence: !input image
  - conditions:
    - '{{ id == "video" }}'
    sequence: !input video